"""Update chunk embedding to use pgvector Vector type

Revision ID: 143af0674e3c
Revises: 002
Create Date: 2025-08-04 15:36:09.723399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '143af0674e3c'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('chunks_embedding_idx', table_name='chunks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('chunks_embedding_idx', 'chunks', ['embedding'], unique=False)
    # ### end Alembic commands ###
