"""Add document structure metadata to Chunk model

Revision ID: 80ec17e8a6ae
Revises: fix_enable_voting
Create Date: 2025-08-05 03:00:39.455871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ec17e8a6ae'
down_revision = 'fix_enable_voting'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('section_title', sa.String(length=255), nullable=True))
    op.add_column('chunks', sa.Column('is_section_header', sa.Boolean(), nullable=True))
    op.add_column('chunks', sa.Column('paragraph_id', sa.Integer(), nullable=True))
    op.add_column('chunks', sa.Column('semantic_group', sa.String(length=255), nullable=True))
    op.add_column('chunks', sa.Column('importance_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'importance_score')
    op.drop_column('chunks', 'semantic_group')
    op.drop_column('chunks', 'paragraph_id')
    op.drop_column('chunks', 'is_section_header')
    op.drop_column('chunks', 'section_title')
    # ### end Alembic commands ###
