"""Add persona order and voting models

Revision ID: ea956b3e4186
Revises: 67b28965a1d3
Create Date: 2025-08-04 18:53:07.411450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea956b3e4186'
down_revision = '67b28965a1d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('model_config_id', sa.Integer(), nullable=False),
    sa.Column('order_position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['model_config_id'], ['model_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'model_config_id', name='uix_persona_order_conversation_model'),
    sa.UniqueConstraint('conversation_id', 'order_position', name='uix_persona_order_conversation_position')
    )
    op.create_index(op.f('ix_persona_orders_id'), 'persona_orders', ['id'], unique=False)
    op.create_table('persona_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('turn_id', sa.Integer(), nullable=False),
    sa.Column('voter_model_config_id', sa.Integer(), nullable=False),
    sa.Column('voted_for_model_config_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ),
    sa.ForeignKeyConstraint(['voted_for_model_config_id'], ['model_configs.id'], ),
    sa.ForeignKeyConstraint(['voter_model_config_id'], ['model_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turn_id', 'voter_model_config_id', name='uix_persona_vote_turn_voter')
    )
    op.create_index(op.f('ix_persona_votes_id'), 'persona_votes', ['id'], unique=False)
    op.drop_index('chunks_embedding_idx', table_name='chunks')
    op.add_column('turns', sa.Column('next_turn_override_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'turns', 'model_configs', ['next_turn_override_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'turns', type_='foreignkey')
    op.drop_column('turns', 'next_turn_override_id')
    op.drop_column('conversations', 'enable_voting')
    op.create_index('chunks_embedding_idx', 'chunks', ['embedding'], unique=False)
    op.drop_index(op.f('ix_persona_votes_id'), table_name='persona_votes')
    op.drop_table('persona_votes')
    op.drop_index(op.f('ix_persona_orders_id'), table_name='persona_orders')
    op.drop_table('persona_orders')
    # ### end Alembic commands ###
